version: '3'

services:
  broker:
    build: broker
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  auldfellas:
    build: auldfellas
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - broker
  dodgydrivers:
    build: dodgydrivers
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - broker
  girlpower:
    build: girlpower
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - broker
  client:
    build: client
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - broker
      - auldfellas
      - dodgydrivers
      - girlpower